In [ ]:
from math import pi, sin, cos, tan, sqrt
import numpy as np

In [ ]:
# RA-DEC values of Sirius, for axample.

ra = 6.75
dec = -(16 + 43 / 60)

In [ ]:
# ALT and AZ values of Sirius, for example.

az = ra # THESE SHOULD BE CONVERTED TO ALT-AZ.
alt = dec  # THESE SHOULD BE CONVERTED TO ALT-AZ.

# Define r to be an arbitrary value, which is the distance to
# the celestial objects, that are assumed to be on the inner surface of a sphere.
r = 10 ** 0

print("Azimuth:\t ", az)
print("Altitude:\t ", alt)

Azimuth:	  6.75
Altitude:	  -16.716666666666665


In [ ]:
# Convert ALT, and AZ from degrees to radians.

az = np.radians(az)
alt = np.radians(alt)

print(az)
print(alt)

0.11780972450961724
-0.29176087329171874


In [ ]:
# Value correction for the used Cartesian coordinate system

theta = 2 * pi - az
phi = pi / 2 - alt
rho = r

print("Theta  \t\tRadians: ", theta, "\tDegrees: ", np.degrees(theta))
print("Phi  \t\tRadians: ", phi, "\tDegrees: ", np.degrees(phi))
print("Rho\t\tunits: ", rho)

Theta  		Radians:  6.165375582669969 	Degrees:  353.25
Phi  		Radians:  1.8625572000866153 	Degrees:  106.71666666666667
Rho		units:  1


In [ ]:
# Converting ALT-AZ coordinates to Cartesian coordinates, for easy manipulation

x = rho * sin(phi) * cos(theta)
y = rho * sin(phi) * sin(theta)
z = rho * cos(phi)

X = np.asarray((x, y, z)).reshape(-1, 1)
print(X)

[[ 0.95110026]
 [-0.11257013]
 [-0.28763913]]


In [ ]:
# Define the tilted and rotated angles (in radians).
# Example values are given.

alpha = np.radians(-32.45)
beta = np.radians(4.5)
gamma = np.radians(-3.76)

In [ ]:
# Define the coefficients of the new coordinates x_, y_, and z_.

r = 1 / sqrt((sin(gamma) ** 2 * sin(alpha) ** 2) + (sin(beta) ** 2 * cos(alpha) ** 2) +
 (sin(alpha) ** 2 * sin(beta) ** 2) + (sin(gamma) ** 2 * cos(alpha) ** 2) + 1)

p = r * (sin(gamma) * sin(alpha) - sin(beta) * cos(alpha))

q = r * (sin(alpha) * sin(beta) + sin(gamma) * cos(alpha))

x_ = np.asarray([[cos(alpha)], [-sin(alpha)], [sin(beta)]])
y_ = np.asarray([[sin(alpha)], [cos(alpha)], [-sin(gamma)]])
z_ = np.asarray([[p], [q], [r]])

In [ ]:
# Defining the transformation matrix

A = np.concatenate((x_, y_, z_), axis=1)
print(A)

[[ 0.84386001 -0.53656341 -0.03086119]
 [ 0.53656341  0.84386001 -0.09693088]
 [ 0.0784591   0.06557729  0.99481254]]


In [ ]:
# Finding new coordinates

transformed = np.matmul(np.linalg.inv(A), X)

x_new = transformed[0][0]
y_new = transformed[1][0]
z_new = transformed[2][0]

print(transformed)

print(x_new, y_new, z_new)

[[ 0.71842076]
 [-0.62518944]
 [-0.30458758]]
0.7184207569218727 -0.6251894393952467 -0.3045875780495587


In [ ]:
# Converting new Cartesian coordinates to ALT, and AZ.

theta_ = np.arctan2(y_new, x_new) # gives answer in the range -pi to pi
if theta_ < 0: theta_ += 2 * pi # convert to 0 - 2pi range

phi_ = np.arctan2(x_new, z_new * cos(theta_)) # gives answer in the range -pi to pi, this is correct.
if phi_ < 0: phi_ += pi

az_ = 2 * pi - theta_
alt_ = pi / 2 - phi_

print("theta_  \tRadians: ", theta_, "\tDegrees: ", np.degrees(theta_))
print("phi_  \t\tRadians: ", phi_, "\tDegrees: ", np.degrees(phi_))
print("az_  \t\tRadians: ", az_, "\tDegrees: ", np.degrees(az_))
print("alt_  \t\tRadians: ", alt_, "\tDegrees: ", np.degrees(alt_))

theta_  	Radians:  5.567064765314443 	Degrees:  318.96931532850573
phi_  		Radians:  1.8803395013462783 	Degrees:  107.73551747887552
az_  		Radians:  0.7161205418651431 	Degrees:  41.03068467149428
alt_  		Radians:  -0.3095431745513817 	Degrees:  -17.735517478875522
